# Generated by Django 2.2.5 on 2019-10-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(default='Office 112b – 115 Block C, JHB 55 Empire Road, Parktown', max_length=250)),
                ('Call', models.CharField(default='+27 (0) 11 482 7256', max_length=250)),
                ('email', models.EmailField(default='info@empowaworx.co.za', max_length=70)),
            ],
        ),
    ]
