# Generated by Django 2.2.5 on 2020-01-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='form',
        ),
        migrations.RemoveField(
            model_name='event_form',
            name='isComplete',
        ),
        migrations.AddField(
            model_name='event_form',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Company'),
        ),
    ]
