# Generated by Django 2.2.5 on 2019-10-04 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='division',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.ForeignKey(db_column='event_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Division'),
            preserve_default=False,
        ),
    ]
