# Generated by Django 2.2.5 on 2019-10-12 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_auto_20191004_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Guests', to=settings.AUTH_USER_MODEL),
        ),
    ]
