# Generated by Django 2.2.5 on 2019-11-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='Image',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
