# Generated by Django 2.2.5 on 2019-11-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_social_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Call',
            new_name='call',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='termscondition',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='social',
            name='Image',
        ),
        migrations.AddField(
            model_name='social',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
