# Generated by Django 2.2.5 on 2019-11-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20191113_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='image',
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
