# Generated by Django 2.2.5 on 2019-11-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20191114_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.Division'),
        ),
    ]
