# Generated by Django 2.2.5 on 2019-11-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20191121_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_form',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Contact'),
        ),
    ]
