# Generated by Django 2.2.5 on 2019-11-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20191121_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='company',
        ),
        migrations.AddField(
            model_name='event_form',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='event.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_form',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='event.Attendee'),
        ),
    ]
