# Generated by Django 2.2.5 on 2019-11-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_attendee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_form',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='event_form',
            name='company',
        ),
        migrations.RemoveField(
            model_name='event_form',
            name='contact',
        ),
        migrations.AddField(
            model_name='attendee',
            name='Form',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='event.Event_Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='Form',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='event.Event_Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='Form',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='event.Event_Form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='event_form',
            name='hear',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event_form',
            name='previous',
            field=models.TextField(blank=True),
        ),
    ]
