# Generated by Django 2.2.5 on 2019-11-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20191129_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='Form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Form'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Form'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='event.Event_Form'),
        ),
    ]
