# Generated by Django 2.2.5 on 2019-12-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20191129_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
        migrations.AddField(
            model_name='event_form',
            name='isComplete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
