# Generated by Django 2.2.5 on 2019-12-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20191201_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_form',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AlterField(
            model_name='event_form',
            name='hear',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_form',
            name='previous',
            field=models.TextField(blank=True, null=True),
        ),
    ]
