# Generated by Django 2.2.5 on 2019-12-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20191201_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='Form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='event.Event_Form'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='event.Event_Form'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='event.Event_Form'),
        ),
    ]
