# Generated by Django 2.2.5 on 2019-12-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_auto_20191201_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='Form',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Form',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Form',
            new_name='form',
        ),
    ]
